apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: flexjar-infoskjerm
  namespace: flex
  annotations:
    snorlax.nais.io/enabled: 'false'
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://flex-docs.intern.dev.nav.no
    - https://flex-docs.ekstern.dev.nav.no
  replicas:
    min: 2
    max: 3
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: /api/internal/preStop
      port: 8080
  azure:
    application:
      allowAllUsers: false
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: '84169515-62b4-4b6f-b07c-952cbb3f20b6' #flex-infoskjerm
          - id: '7d275d5e-59a5-473d-b530-a9091b3de4c6'
    sidecar:
      enabled: true
      autoLogin: false

  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 100m
      memory: 350Mi
  liveness:
    path: /api/internal/isAlive
  readiness:
    path: /api/internal/isAlive
  startup:
    path: /api/internal/isAlive
    initialDelay: 10
  accessPolicy:
    outbound:
      external: # bruk nslookup mot api.trello.com og raw.githubusercontent.com og legg inn de nye ipene her
        - ipv4: 185.166.143.18
        - ipv4: 185.166.143.19
        - ipv4: 185.166.143.20
        - ipv4: 185.166.143.21
        - ipv4: 185.166.143.22
        - ipv4: 185.166.143.23
        - ipv4: 185.166.143.24
        - ipv4: 185.166.143.25
        - ipv4: 185.166.143.26
        - ipv4: 185.199.108.133
        - ipv4: 185.199.109.133
        - ipv4: 185.199.110.133
        - ipv4: 185.199.111.133
        - ipv4: 143.204.55.107
        - ipv4: 143.204.55.8
        - ipv4: 143.204.55.75
        - ipv4: 143.204.55.11
        - ipv4: 18.165.122.45
        - ipv4: 18.165.122.62
        - ipv4: 18.165.122.95
        - ipv4: 18.165.122.48
        - ipv4: 108.157.214.125
        - ipv4: 108.157.214.91
        - ipv4: 108.157.214.29
        - ipv4: 108.157.214.20

  envFrom:
    - secret: flexjar-infoskjerm-trello-secrets
  env:
    - name: TRELLO_OKR_BOARD
      value: 0gO6UCsS
    - name: TRELLO_RETRO_BOARD
      value: Tx2MZJyC
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /.next/cache
  gcp:
    bigQueryDatasets:
      - name: flex_trellodocs_dataset
        permission: READWRITE
