apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: flexjar-infoskjerm
  namespace: flex
  annotations:
    snorlax.nais.io/enabled: 'false'
  labels:
    team: flex
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - {{ingress}}
  replicas:
    min: 2
    max: 3
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: /api/internal/preStop
      port: 3000
  azure:
    application:
      enabled: true
      tenant: nav.no

  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 100m
      memory: 350Mi
  liveness:
    path: /api/internal/isAlive
  readiness:
    path: /api/internal/isAlive
  startup:
    path: /api/internal/isAlive
    initialDelay: 10
  accessPolicy:
    outbound:
      rules:
        - application: flexjar-backend
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
